require: rubocop-rails

AllCops:
  DisabledByDefault: true
  SuggestExtensions: false
Style/IndentationConsistency:
  Enabled: true
Layout/LineLength:
  Max: 200
Layout/EmptyLines:
  Enabled: true
Rails/HasManyOrHasOneDependent:
  Enabled: true
Rails/ActionFilter:
  Enabled: true
Rails/AddColumnIndex:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/CreateTableWithTimestamps:
  Enabled: true
